### PR TITLE
New image naming

### PR DESCRIPTION
**Pull request by drew-viles**
New image naming convention that will generate a UUIDv4, pull the 8 characters before the first hyphen and then prepend "PREFIX". 

resulting in something like `eck-230323-abcdefgh`

This also contains a few fixes to allow the image to build thanks to new flatcar additions and subsequent adjustments around volume type & image format
#11

### CODE REVIEW

**Comment by yankcrime** [comment]
@srelf-eschercloud needs to get involved in this as he loves a conversation about naming things.

**Comment by drew-viles** [comment]
Indeed. I disagree with ChaptGPT anyway 🤣 
image

**Review by yankcrime — APPROVED** [review]
I'd make some suggestions about the `Dockerfile` but they're outside the scope of this PR so  I'll leave it.

**Comment by drew-viles** [comment]
Feel free to make them here as I'm making changes to it as it stands :-p

https://github.com/eschercloudai/baski/pull/27/files

**Pull request merged**
